#!/usr/bin/env bash
# Bash script that displays Best School 10 times, Using the while loop.

count=1

while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo -e "Best School\nHi";
		((count++))
	else
		echo "Best School";
		((count++))
	fi
done
