#!/usr/bin/env bash
# Bash script that displays Best School 10 times, Using the while loop.

count=1

while [ $count -le 20 ]; do
	case $count in
		4)
			echo -e "4\nbad luck from China";
			((count++))
			;;
		9)
			echo -e "9\nbad luck from Japan";
			((count++))
			;;
		17)
			echo -e "17\nbad luck from Italy"
			((count++))
			;;
		*)
			echo "$count";
			((count++))
			;;
	esac
done
